#!/usr/bin/env bash
# Kills the 4-to_infinity_and_beyond

#get the pid of the program
id=$(pgrep "bash ./4-to_infinity_and_beyond" -f)

#terminate the ifinate loop
if [ -n "$id" ]
then
kill -15 "$id"
fi
